const data = {
  products: [
    {
      _id: 1,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic1.jpg",
      price: 124,
      brand: "Nike",
      rating: 3.5,
      reivews: 54,
      description: "this is a good nike shirt",
    },
    {
      _id: 2,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic2.jpg",
      price: 124,
      brand: "Nike",
      rating: 4.5,
      reivews: 34,
      description: "this is a good nike shirt",
    },
    {
      _id: 3,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic3.jpg",
      price: 124,
      brand: "Nike",
      rating: 3,
      reivews: 154,
      description: "this is a good nike shirt",
    },
    {
      _id: 4,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic4.jpg",
      price: 124,
      brand: "Nike",
      rating: 1.5,
      reivews: 544,
      description: "this is a good nike shirt",
    },
    {
      _id: 5,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic5.jpg",
      price: 124,
      brand: "Nike",
      rating: 4.5,
      reivews: 543,
      description: "this is a good nike shirt",
    },
    {
      _id: 6,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic6.jpg",
      price: 124,
      brand: "Nike",
      rating: 5,
      reivews: 354,
      description: "this is a good nike shirt",
    },
    {
      _id: 7,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic7.jpg",
      price: 124,
      brand: "Nike",
      rating: 4,
      reivews: 654,
      description: "this is a good nike shirt",
    },
    {
      _id: 8,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic8.jpg",
      price: 124,
      brand: "Nike",
      rating: 5,
      reivews: 254,
      description: "this is a good nike shirt",
    },
    {
      _id: 9,
      name: "Nike slim shirt",
      category: "Shirt",
      image: "/images/pic9.jpg",
      price: 124,
      brand: "Nike",
      rating: 3.5,
      reviews: 451,
      description: "this is a good nike shirt",
    },
  ],
};

export default data;
